# Generated by Django 3.2.16 on 2024-10-10 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Данный ник уже используется'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Ввидите другое имя пользователя', regex='^[\\w.@+-]+$')], verbose_name='Имя пользователя'),
        ),
    ]
